# Generated by Django 4.2.1 on 2023-06-06 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0009_publisher_alter_book_publisher"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"verbose_name": "Книга", "verbose_name_plural": "Книги"},
        ),
        migrations.AlterField(
            model_name="book",
            name="publisher",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="books.publisher",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="raiting",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="tags",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="books", to="books.tag"
            ),
        ),
    ]
