# Generated by Django 4.2.1 on 2023-06-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0010_alter_book_options_alter_book_publisher_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="tags",
            field=models.ManyToManyField(related_name="books", to="books.tag"),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="language",
            field=models.CharField(
                choices=[("ru", "Russian"), ("en", "English"), ("fr", "French")],
                max_length=2,
            ),
        ),
    ]
