# Generated by Django 4.2.1 on 2023-06-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0014_book_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to=""),
        ),
    ]
